export const GET_TRENDING_COURSES_LIST_REQUEST =
  'GET_TRENDING_COURSES_LIST_REQUEST';
export const GET_TRENDING_COURSES_LIST_SUCCESS =
  'GET_TRENDING_COURSES_LIST_SUCCESS';
export const GET_TRENDING_COURSES_LIST_FAIL = 'GET_TRENDING_COURSES_LIST_FAIL';
