export const GET_TRENDING_COURSES_LIST_REQUEST =
  'GET_TRENDING_COURSES_LIST_REQUEST';
export const GET_TRENDING_COURSES_LIST_SUCCESS =
  'GET_TRENDING_COURSES_LIST_SUCCESS';
export const GET_TRENDING_COURSES_LIST_FAIL = 'GET_TRENDING_COURSES_LIST_FAIL';

export const GET_COURSE_BY_SLUG_SUCCESS = 'GET_COURSE_BY_SLUG_SUCCESS';
export const GET_COURSE_BY_SLUG_FAIL = 'GET_COURSE_BY_SLUG_FAIL';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';
