export const GET_QUESTION_LIST_REQUEST = 'GET_QUESTION_LIST_REQUEST';
export const GET_QUESTION_LIST_SUCCESS = 'GET_QUESTION_LIST_SUCCESS';
export const GET_QUESTION_LIST_FAIL = 'GET_QUESTION_LIST_FAIL';

export const GET_QUESTION_DETAIL = 'GET_QUESTION_DETAIL';

export const CHOSEN_QUESTION_RADIO = 'CHOSEN_QUESTION';
export const CHOSEN_QUESTION_CHECKBOXES = 'CHOSEN_QUESTION_CHECKBOXES';
